nelmio_cors:
    defaults:
    # paths:
    #     '^/': 
        # origin_regex: true
        # allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_origin: ['*']
        # allow_credentials: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        # expose_headers: ['Link']
        # max_age: 3600

